grpc:
  port: 6565
  tls:
    enabled: ${GRPC_SSL_ENABLED:false}
    certChainFile: ${GRPC_CERT:/app/certChainFile.crt}
    privateKeyFile: ${GRPC_KEY:/app/privateKeyFile.pem}
    trustCertCollectionFile: ${GRPC_TRUST_CERT:/app/trustCertCollectionFile.crt}
    cacheTrustCertCollectionFile: ${GRPC_CACHE_TRUST_CERT:/app/cacheTrustCertCollectionFile.crt}
    cacheClientCertChainFile: ${GRPC_CACHE_CERT:/app/cacheClientCertChainFile.crt}
    cacheClientPrivateKeyFile: ${GRPC_CACHE_KEY:/app/cacheClientPrivateKeyFile.pem}

flair-cache:
  enabled: false

app:
  auth:
    jwt-key: ${GRPC_JWT_KEY:secretKey1secretKey1secretKey1secretKey1secretKey1secretKey1secretKey1}
  drivers:
    dir: ${DRIVERS_DIR:/var/drivers}
    names:
      - "com.simba.googlebigquery.jdbc42.Driver"
---
spring:
  profiles: dev
